* pdftotext

** table of contents

| source |                             |                        |
|  block | content                     | block name             |
|--------+-----------------------------+------------------------|
|     05 | blank, sh, session, raw     |                        |
|        |                             |                        |
|     15 | define file name to process | the_pdf_name_block     |
|        |                             | <<the_pdf_name_block>> |
|        |                             |                        |
|     17 | extract pdf content         |                        |
|        |                             |                        |
|        |                             |                        |

** source block 05, blank template, session, raw, sh

| step | goal                     | target           |
|------+--------------------------+------------------|

#+NAME:
#+HEADERS: :session
#+HEADERS: :results raw
#+BEGIN_SRC sh


#+END_SRC

#+RESULTS:


** source block 07, long variable assignment

| step | goal                     | target           |
|------+--------------------------+------------------|

#+NAME:
#+HEADERS: :session
#+HEADERS: :results raw
#+BEGIN_SRC sh

test=$(printf 
'1'
2
3
)

# echo $test 

echo $test | sed -r 's/([0-9]) /\1 \n/g'

test1=$(echo $test | sed -r 's/([0-9]) /\1 \n/g')

echo 'test1 is' $test1

#+END_SRC

#+RESULTS:

test1 is
'1' 2 
3
test1 is '1' 2 3
1 
2 
3
test1 is 1 2 3
1 
2 
3
test1 is 1 2 3






** source block 15, define pdf file name #+NAME: the_pdf_name_block

| step | goal                     | target           |
|------+--------------------------+------------------|
|      | define the pdf file name | the_pdf_filename |
|      |                          |                  |
|      | print the file name      |                  |

#+NAME: the_pdf_name_block
#+HEADERS: :session
#+HEADERS: :results raw
#+BEGIN_SRC sh


 the_pdf_filename="en_codeformat.pdf"  #A
# the_pdf_filename="en_codedescribe.pdf"  #B


echo

# echo "\$the_pdf_filename is:" $the_pdf_filename

# echo "the_dir_under_home is" $the_dir_under_home

# echo "the_file_name is" $the_file_name

# echo "the_pdf_path is"  $the_pdf_path

# printf "The current directory, by default, through the command pwd, is: " ; pwd

#+END_SRC

#+RESULTS: the_pdf_name_block

$the_pdf_filename is: en_codeformat.pdf






** source block 17, extract raw text between page f, l through pdftotext

#+NAME: raw_output
#+HEADERS: :noweb yes
#+HEADERS: :results raw
#+HEADERS: :session
#+BEGIN_SRC sh
<<the_pdf_name_block>>

pdftotext -f 1 -l 3 -raw -nopgbrk $the_pdf_filename -
#+END_SRC


    

** source block 25, sed 

#+HEADERS: :noweb yes
#+HEADERS: :results raw
#+HEADERS: :session
#+BEGIN_SRC sh
 <<the_pdf_name_block>>

 raw_test=$(pdftotext -f 1 -l 2 -raw -nopgbrk $the_pdf_filename -)

 echo $raw_test

 echo $raw_test | sed -r 's/[.]{2,}/|/g' | sed -r 's/([0-9]+ )/\1\n/g'

#+END_SRC


** source block A.1 檔案格式及資料描述

#+NAME: raw_output
#+HEADERS: :noweb yes
#+HEADERS: :results raw
#+HEADERS: :session
#+BEGIN_SRC sh
<<the_pdf_name_block>>

pdftotext -f 1 -l 3 -raw -nopgbrk $the_pdf_filename -

#+END_SRC


    


** source block A.2 檔案格式及資料描述

#+NAME: raw_output
#+HEADERS: :noweb yes
#+HEADERS: :results raw
#+HEADERS: :session
#+BEGIN_SRC sh
<<the_pdf_name_block>>

# pdftotext -f 1 -l 3 -raw -nopgbrk $the_pdf_filename -

raw_test=$(pdftotext -f 1 -l 3 -raw -nopgbrk $the_pdf_filename -)

  echo $raw_test
  echo $raw_test | sed -r 's/[.]{2,}/,/g'
  echo $raw_test | sed -r 's/[.]{2,}/,/g' | sed -r 's/(A-[0-9]+ )/\1\n/g'


#+END_SRC

#+RESULTS: raw_output

A-I V.102-11 目 錄 第一部份：檔案格式及資料描述 醫事機構基本資料檔（HOSB）................................................................. A-1 醫事機構副檔資料檔（HOSX）................................................................. A-3 醫事機構服務項目檔（HOX）................................................................... A-5 醫事機構診療科別明細檔（DETA） ......................................................... A-6 醫事機構病床主檔（BED）........................................................................ A-7 醫事人員基本資料檔（PER） .................................................................... A-8 專科醫師證書主檔（DOC）[適用 86～100 年資料] ................................ A-9 專科醫師證書主檔（DOC）[適用 101 年以後資料] .............................. A-10 評鑑資料檔（HOSP_GRAD）...................................................................A-11 醫事機構類別明細檔（HOSTDTL） ....................................................... A-12 執業資料紀錄檔（LIC） ........................................................................... A-13 重大傷病證明明細檔（HV）[適用 85～93 年資料]............................... A-14 重大傷病證明明細檔（HV）[適用 94～98 年資料]............................... A-15 重大傷病證明明細檔（HV）[適用 99~100 年以後資料]....................... A-16 重大傷病證明明細檔（HV）[適用 101 年以後資料]............................. A-17 門診費用申請總表主檔（CT）[適用 100 年以前資料].......................... A-18 V.102-11 A-II 門診費用申請總表主檔（CT）[適用 101 年以後資料] ........................ A-20 住院費用申請總表主檔（DT）[適用 100 年以前資料].......................... A-22 住院費用申請總表主檔（DT）[適用 101 年以後資料].......................... A-23 門診處方及治療明細檔（CD）[適用 86～92 年資料] ........................... A-25 門診處方及治療明細檔（CD）[適用 93~100 年資料]........................... A-30 門診處方及治療明細檔（CD）[適用 101 年以後資料] ......................... A-35 門診處方醫令明細檔（OO）[適用 85～95 年資料]............................... A-41 門診處方醫令明細檔（OO）[適用 96~100 年資料]............................... A-43 門診處方醫令明細檔（OO）[適用 101 年以後資料]............................. A-46 住院醫療費用清單明細檔（DD）[適用 85～92 年資料]....................... A-50 住院醫療費用清單明細檔（DD）[適用 93～95 年資料]....................... A-55 住院醫療費用清單明細檔（DD）[適用 96~100 年資料]....................... A-60 住院醫療費用清單明細檔（DD）[適用 101 年以後資料]..................... A-65 住院醫療費用醫令清單明細檔（DO）[適用 85～95 年資料]............... A-71 住院醫療費用醫令清單明細檔（DO）[適用 96～98 年資料]............... A-72 住院醫療費用醫令清單明細檔（DO）[適用 99~100 年資料]............... A-74 住院醫療費用醫令清單明細檔（DO）[適用 101 年以後資料]............. A-76 特約藥局處方及調劑明細檔（GD）[適用 85～87 年資料]................... A-79 特約藥局處方及調劑明細檔（GD）[適用 88～92 年資料]................... A-80 A-III V.102-11 特約藥局處方及調劑明細檔（GD）[適用 93～98 年資料]................... A-82 特約藥局處方及調劑明細檔（GD）[適用 99~100 年資料]................... A-84 特約藥局處方及調劑明細檔（GD）[適用 101 年以後資料]................. A-86 特約藥局處方調劑醫令檔（GO）[適用 85～95 年資料]....................... A-88 特約藥局處方調劑醫令檔（GO）[適用 96~100 年資料]....................... A-89 特約藥局處方調劑醫令檔（GO）[適用 101 年以後資料]..................... A-90 物理治療所調劑明細檔（GDD）............................................................. A-91 物理治療所調劑醫令檔（GOO）............................................................. A-93 承保資料檔（ID）[適用 98 年以前資料]................................................. A-94 承保資料檔（ID）[適用 99 年以後資料]................................................. A-96 藥品主檔（DRUG） .................................................................................. A-97 ※本譯碼簿僅供參考，資料描述或代碼說明資訊如有異動，請逕自全民健康保險 署網站（http://www.nhi.gov.tw/）查閱。
A-I V.102-11 目 錄 第一部份：檔案格式及資料描述 醫事機構基本資料檔（HOSB）, A-1 醫事機構副檔資料檔（HOSX）, A-3 醫事機構服務項目檔（HOX）, A-5 醫事機構診療科別明細檔（DETA） , A-6 醫事機構病床主檔（BED）, A-7 醫事人員基本資料檔（PER） , A-8 專科醫師證書主檔（DOC）[適用 86～100 年資料] , A-9 專科醫師證書主檔（DOC）[適用 101 年以後資料] , A-10 評鑑資料檔（HOSP_GRAD）,A-11 醫事機構類別明細檔（HOSTDTL） , A-12 執業資料紀錄檔（LIC） , A-13 重大傷病證明明細檔（HV）[適用 85～93 年資料], A-14 重大傷病證明明細檔（HV）[適用 94～98 年資料], A-15 重大傷病證明明細檔（HV）[適用 99~100 年以後資料], A-16 重大傷病證明明細檔（HV）[適用 101 年以後資料], A-17 門診費用申請總表主檔（CT）[適用 100 年以前資料], A-18 V.102-11 A-II 門診費用申請總表主檔（CT）[適用 101 年以後資料] , A-20 住院費用申請總表主檔（DT）[適用 100 年以前資料], A-22 住院費用申請總表主檔（DT）[適用 101 年以後資料], A-23 門診處方及治療明細檔（CD）[適用 86～92 年資料] , A-25 門診處方及治療明細檔（CD）[適用 93~100 年資料], A-30 門診處方及治療明細檔（CD）[適用 101 年以後資料] , A-35 門診處方醫令明細檔（OO）[適用 85～95 年資料], A-41 門診處方醫令明細檔（OO）[適用 96~100 年資料], A-43 門診處方醫令明細檔（OO）[適用 101 年以後資料], A-46 住院醫療費用清單明細檔（DD）[適用 85～92 年資料], A-50 住院醫療費用清單明細檔（DD）[適用 93～95 年資料], A-55 住院醫療費用清單明細檔（DD）[適用 96~100 年資料], A-60 住院醫療費用清單明細檔（DD）[適用 101 年以後資料], A-65 住院醫療費用醫令清單明細檔（DO）[適用 85～95 年資料], A-71 住院醫療費用醫令清單明細檔（DO）[適用 96～98 年資料], A-72 住院醫療費用醫令清單明細檔（DO）[適用 99~100 年資料], A-74 住院醫療費用醫令清單明細檔（DO）[適用 101 年以後資料], A-76 特約藥局處方及調劑明細檔（GD）[適用 85～87 年資料], A-79 特約藥局處方及調劑明細檔（GD）[適用 88～92 年資料], A-80 A-III V.102-11 特約藥局處方及調劑明細檔（GD）[適用 93～98 年資料], A-82 特約藥局處方及調劑明細檔（GD）[適用 99~100 年資料], A-84 特約藥局處方及調劑明細檔（GD）[適用 101 年以後資料], A-86 特約藥局處方調劑醫令檔（GO）[適用 85～95 年資料], A-88 特約藥局處方調劑醫令檔（GO）[適用 96~100 年資料], A-89 特約藥局處方調劑醫令檔（GO）[適用 101 年以後資料], A-90 物理治療所調劑明細檔（GDD）, A-91 物理治療所調劑醫令檔（GOO）, A-93 承保資料檔（ID）[適用 98 年以前資料], A-94 承保資料檔（ID）[適用 99 年以後資料], A-96 藥品主檔（DRUG） , A-97 ※本譯碼簿僅供參考，資料描述或代碼說明資訊如有異動，請逕自全民健康保險 署網站（http://www.nhi.gov.tw/）查閱。


V.102-11 
目 錄 
第一部份：檔案格式及資料描述 

| 醫事機構基本資料檔（HOSB）                            | A-1  |
| 醫事機構副檔資料檔（HOSX）                            | A-3  |
| 醫事機構服務項目檔（HOX）                             | A-5  |
| 醫事機構診療科別明細檔（DETA）                        | A-6  |
| 醫事機構病床主檔（BED）                               | A-7  |
| 醫事人員基本資料檔（PER）                             | A-8  |
| 專科醫師證書主檔（DOC）[適用 86～100 年資料]          | A-9  |
| 專科醫師證書主檔（DOC）[適用 101 年以後資料]          | A-10 |
| 評鑑資料檔（HOSP_GRAD）                               | A-11 |
| 醫事機構類別明細檔（HOSTDTL）                         | A-12 |
| 執業資料紀錄檔（LIC）                                 | A-13 |
| 重大傷病證明明細檔（HV）[適用 85～93 年資料]          | A-14 |
| 重大傷病證明明細檔（HV）[適用 94～98 年資料]          | A-15 |
| 重大傷病證明明細檔（HV）[適用 99~100 年以後資料]      | A-16 |
| 重大傷病證明明細檔（HV）[適用 101 年以後資料]         | A-17 |
| 門診費用申請總表主檔（CT）[適用 100 年以前資料]       | A-18 |
| 門診費用申請總表主檔（CT）[適用 101 年以後資料]       | A-20 |
| 住院費用申請總表主檔（DT）[適用 100 年以前資料]       | A-22 |
| 住院費用申請總表主檔（DT）[適用 101 年以後資料]       | A-23 |
| 門診處方及治療明細檔（CD）[適用 86～92 年資料]        | A-25 |
| 門診處方及治療明細檔（CD）[適用 93~100 年資料]        | A-30 |
| 門診處方及治療明細檔（CD）[適用 101 年以後資料]       | A-35 |
| 門診處方醫令明細檔（OO）[適用 85～95 年資料]          | A-41 |
| 門診處方醫令明細檔（OO）[適用 96~100 年資料]          | A-43 |
| 門診處方醫令明細檔（OO）[適用 101 年以後資料]         | A-46 |
| 住院醫療費用清單明細檔（DD）[適用 85～92 年資料]      | A-50 |
| 住院醫療費用清單明細檔（DD）[適用 93～95 年資料]      | A-55 |
| 住院醫療費用清單明細檔（DD）[適用 96~100 年資料]      | A-60 |
| 住院醫療費用清單明細檔（DD）[適用 101 年以後資料]     | A-65 |
| 住院醫療費用醫令清單明細檔（DO）[適用 85～95 年資料]  | A-71 |
| 住院醫療費用醫令清單明細檔（DO）[適用 96～98 年資料]  | A-72 |
| 住院醫療費用醫令清單明細檔（DO）[適用 99~100 年資料]  | A-74 |
| 住院醫療費用醫令清單明細檔（DO）[適用 101 年以後資料] | A-76 |
| 特約藥局處方及調劑明細檔（GD）[適用 85～87 年資料]    | A-79 |
| 特約藥局處方及調劑明細檔（GD）[適用 88～92 年資料]    | A-80 |
| 特約藥局處方及調劑明細檔（GD）[適用 93～98 年資料]    | A-82 |
| 特約藥局處方及調劑明細檔（GD）[適用 99~100 年資料]    | A-84 |
| 特約藥局處方及調劑明細檔（GD）[適用 101 年以後資料]   | A-86 |
| 特約藥局處方調劑醫令檔（GO）[適用 85～95 年資料]      | A-88 |
| 特約藥局處方調劑醫令檔（GO）[適用 96~100 年資料]      | A-89 |
| 特約藥局處方調劑醫令檔（GO）[適用 101 年以後資料]     | A-90 |
| 物理治療所調劑明細檔（GDD）                           | A-91 |
| 物理治療所調劑醫令檔（GOO）                           | A-93 |
| 承保資料檔（ID）[適用 98 年以前資料]                  | A-94 |
| 承保資料檔（ID）[適用 99 年以後資料]                  | A-96 |
| 藥品主檔（DRUG）                                      | A-97 | 

  
※本譯碼簿僅供參考，資料描述或代碼說明資訊如有異動，請逕自全民健康保險 署網站（http://www.nhi.gov.tw/）查閱。

    




** source block B, 代碼說明 B

#+HEADERS: :noweb yes
#+HEADERS: :results raw
#+HEADERS: :session
#+BEGIN_SRC sh
 <<the_pdf_name_block>>

 raw_test=$(pdftotext -f 1 -l 2 -raw -nopgbrk $the_pdf_filename -)



  echo $raw_test
  echo $raw_test | sed -r 's/[.]{2,}/|/g'
  echo $raw_test | sed -r 's/[.]{2,}/|/g' | sed -r 's/([0-9]+ )/\1\n/g'

#+END_SRC

#+RESULTS:

B-I 目 錄 第二部份：代碼說明 評鑑等級...................................................................................................B-1 特約類別...................................................................................................B-3 權屬別及型態別其代號與名稱...............................................................B-4 特約狀況碼...............................................................................................B-9 醫事人員類別.........................................................................................B-10 病床類別.................................................................................................B-11 地區代碼、名稱、分局及郵遞區號.....................................................B-13 案件分類.................................................................................................B-26 健保卡就醫序號（預防保健服務時程代碼）.....................................B-35 部分負擔代號及相關規定.....................................................................B-40 就醫科別及細分科.................................................................................B-49 診療科別.................................................................................................B-51 專科醫師代號、科別.............................................................................B-53 特定治療項目代號.................................................................................B-55 給付類別.................................................................................................B-64 處方調劑方式.........................................................................................B-65 B-II 不適用 TW_DRGS 案件特殊註記.......................................................B-66 住院醫令類別.........................................................................................B-67 住院醫令代碼.........................................................................................B-68 診療部位申報方式.................................................................................B-72 單位屬性代號.........................................................................................B-74 加退保別說明.........................................................................................B-76 身份別說明.............................................................................................B-77 全民健康保險重大傷病範圍.................................................................B-78 串檔說明.................................................................................................B-79 ※本譯碼簿僅供參考，資料描述或代碼說明資訊如有異動，請逕自中 央健康保險署網站（http://www.nhi.gov.tw/）查閱。
B-I 目 錄 第二部份：代碼說明 評鑑等級|B-1 特約類別|B-3 權屬別及型態別其代號與名稱|B-4 特約狀況碼|B-9 醫事人員類別|B-10 病床類別|B-11 地區代碼、名稱、分局及郵遞區號|B-13 案件分類|B-26 健保卡就醫序號（預防保健服務時程代碼）|B-35 部分負擔代號及相關規定|B-40 就醫科別及細分科|B-49 診療科別|B-51 專科醫師代號、科別|B-53 特定治療項目代號|B-55 給付類別|B-64 處方調劑方式|B-65 B-II 不適用 TW_DRGS 案件特殊註記|B-66 住院醫令類別|B-67 住院醫令代碼|B-68 診療部位申報方式|B-72 單位屬性代號|B-74 加退保別說明|B-76 身份別說明|B-77 全民健康保險重大傷病範圍|B-78 串檔說明|B-79 ※本譯碼簿僅供參考，資料描述或代碼說明資訊如有異動，請逕自中 央健康保險署網站（http://www.nhi.gov.tw/）查閱。
B-I 目 錄 第二部份：代碼說明 評鑑等級|B-1 
特約類別|B-3 
權屬別及型態別其代號與名稱|B-4 
特約狀況碼|B-9 
醫事人員類別|B-10 
病床類別|B-11 
地區代碼、名稱、分局及郵遞區號|B-13 
案件分類|B-26 
健保卡就醫序號（預防保健服務時程代碼）|B-35 
部分負擔代號及相關規定|B-40 
就醫科別及細分科|B-49 
診療科別|B-51 
專科醫師代號、科別|B-53 
特定治療項目代號|B-55 
給付類別|B-64 
處方調劑方式|B-65 
B-II 不適用 TW_DRGS 案件特殊註記|B-66 
住院醫令類別|B-67 
住院醫令代碼|B-68 
診療部位申報方式|B-72 
單位屬性代號|B-74 
加退保別說明|B-76 
身份別說明|B-77 
全民健康保險重大傷病範圍|B-78 
串檔說明|B-79 
※本譯碼簿僅供參考，資料描述或代碼說明資訊如有異動，請逕自中 央健康保險署網站（http://www.nhi.gov.tw/）查閱。


** source block B-1, 評鑑等級

#+HEADERS: :noweb yes
#+HEADERS: :results raw
#+HEADERS: :session
#+BEGIN_SRC sh
 <<the_pdf_name_block>>

 raw_test=$(pdftotext -f 3 -l 4 -nopgbrk -raw $the_pdf_filename -)

#  echo $raw_test | sed -r 's/([0-79][0-9]) /\n\1, /g'
#  echo $raw_test | sed -r 's/([0-79][0-9]) /\n\1, /g' | sed -r 's/( 8[89] )/,\1/g'
   echo $raw_test | sed -r 's/([0-79][0-9]) /\n\1, /g' | sed -r 's/( 8[89] )/,\1/g' | sed -r 's/( 評鑑制度 )/,\1/g' 


#+END_SRC







 

** source block B-3, 特約類別

#+HEADERS: :noweb yes
#+HEADERS: :results raw
#+HEADERS: :session
#+BEGIN_SRC sh
 <<the_pdf_name_block>>

            pdftotext -f 5 -l 5 -nopgbrk -raw $the_pdf_filename -

#+END_SRC

#+RESULTS:
B-3 特約類別 
|      |                  |                                                 |
| 代碼 | 名稱             | 備註                                            |
|------+------------------+-------------------------------------------------|
|    1 | 醫學中心         |                                                 |
|    2 | 區域醫院         |                                                 |
|    3 | 地區醫院         |                                                 |
|    4 | 基層院所         |                                                 |
|    5 | 特約藥局         |                                                 |
|    6 | 居家照護         |                                                 |
|    7 | 精神社區復健     |                                                 |
|    8 | 助產所           |                                                 |
|    9 | 特約醫事檢驗機構 | 92/3 由指定醫事檢驗機構改為特約醫事檢驗機構者。 |
|    A | 物理治療所       | 90/7/1 新增。                                   |
|    B | 放射治療機構     | 97/4 新增                                       |
|    C | 職能治療所       | 97/4 新增                                       |
| W、X | 不詳             |                                                 |







 

** source block B-4, 權屬別及型態別其代號與名稱

#+HEADERS: :noweb yes
#+HEADERS: :results raw
#+HEADERS: :session
#+BEGIN_SRC sh
 <<the_pdf_name_block>>

            pdftotext -f 6 -l 10 -nopgbrk -raw $the_pdf_filename -

#+END_SRC

#+RESULTS:
B-4 權屬別及型態別其代號與名稱

一、醫療機構

| 權屬別 |                              |
|     01 | 署、市立醫院                 |
|     02 | 縣市立醫院                   |
|     04 | 公立醫學院校附設醫院         |
|     05 | 軍方醫院(民眾診療)           |
|     06 | 榮民醫院                     |
|     07 | 機關(構)附設醫院             |
|     08 | 公立中醫醫院                 |
|     09 | 社團法人醫院                 |
|     10 | 宗教社團法人附設醫院         |
|     11 | 財團法人醫院                 |
|     12 | 宗教財團法人附設醫院         |
|     13 | 私立醫學院校附設醫院         |
|     14 | 其他法人附設醫院             |
|     15 | 私立醫院                     |
|     17 | 私立牙醫醫院                 |
|     18 | 私立中醫院                   |
|     21 | 市立診所                     |
|     22 | 縣市立診所                   |
|     23 | 衛生所                       |
|     24 | 公立學校附設醫務室           |
|     25 | 軍方診所(民眾診療附設門診部) |
|     26 | 榮民診所(榮家醫務室)         |
|     27 | 機關(構)附設醫務室           |
|     28 | 公立中醫診所                 |
|     29 | 公益法人所設診所             |
|     30 | 公益法人所設醫務室           |
|     31 | 財團法人附設醫務室           |
|     32 | 宗教財團法人附設診所、醫務室 |
|     33 | 私立學校附設醫務室           |
|     34 | 事業單位附設醫務室           |
|     35 | 私立診所                     |
|     37 | 私立牙醫診所                 |
|     38 | 私立中醫診所                 |
|     40 | 醫療財團法人診所             |
|     41 | 醫療社團法人診所             |
|     42 | 財團法人其他醫療機構         |
|     45 | 私立其他醫療機構             |


|              型態別 |                  |
|---------------------+------------------|
|         醫院：01-08 |                  |
|                  01 | 綜合醫院         |
|                  02 | 醫院             |
|                  03 | 專科醫院         |
|                  04 | 精神科醫院       |
|                  05 | 特殊科醫院       |
|                  06 | 慢性醫院         |
|                  07 | 專科診所         |
|                  08 | 一般診所(醫務室) |
|                  09 | 特殊科診所       |
|---------------------+------------------|
|         牙醫：11-13 |                  |
|                  11 | 牙醫醫院         |
|                 B-5 |                  |
|                  12 | 牙醫專科診所     |
|                  13 | 牙醫一般診所     |
|---------------------+------------------|
|         中醫：21-24 |                  |
|                  21 | 中醫綜合醫院     |
|                  22 | 中醫醫院         |
|                  23 | 中醫專科診所     |
|                  24 | 中醫一般診所     |
|---------------------+------------------|
| 其他醫療機構：41-43 |                  |
|                  41 | 捐血中心         |
|                  42 | 捐血站           |
|                  43 | 病理中心         |

二、藥商

|            權屬別 |                |
|-------------------+----------------|
| 販賣業：51-53、62 |                |
|                51 | 西藥販賣業     |
|                52 | 中藥販賣業     |
|                53 | 醫療器材販賣業 |
|                62 | 販賣業         |
|-------------------+----------------|
| 製造業：54-58、61 |                |
|                54 | 西藥製造業     |
|                55 | 中藥製造業     |
|                56 | 醫療器材製造業 |
|                57 | 明膠膠囊製造業 |
|                58 | 化妝品製造業   |
|                61 | 製造業         |
|-------------------+----------------|
|       其他：59-60 |                |
|                59 | 藥局           |
|                60 | 列冊中藥商     |



| 型態別 |                                    |
|--------+------------------------------------|
|     01 | 藥師自營                           |
|     02 | 藥劑生自營                         |
|     03 | 藥師駐店管理                       |
|     04 | 藥劑生駐店管理                     |
|     05 | 符合藥事法104條規定─藥師管理       |
|     06 | 符合藥事法104條規定─藥劑生管理     |
|     07 | 中醫師駐店管理                     |
|     08 | 中醫師兼管                         |
|     09 | 藥師兼管                           |
|     11 | 確具中藥基本知識及鑑別能力人員管理 |
|     12 | 人用生物藥品製造廠                 |
|     13 | 藥師監製                           |
|     14 | 中醫師監製                         |
|     16 | 列冊中藥商                         |


三、護理護產機構


| 權屬別 |                              |
|--------+------------------------------|
|     71 | 公立護產機構                 |
|     72 | 財團法人護產機構             |
|     73 | 其他法人附設護產機構         |
|     74 | 個人開設護產機構             |
|     75 | 公立醫療機構附設護產機構     |
|     76 | 私立醫療機構附設護產機構     |
|     77 | 財團法人醫療機構附設護產機構 |
|     78 | 其他                         |
|     79 | 社團法人醫療機構附設護產機構 |


| 型態別 |                            |
|--------+----------------------------|
|     01 | 護理之家                   |
|     02 | 居家護理                   |
|     03 | 產後護理                   |
|     04 | 助產所                     |
|     05 | 學校醫務室─校護            |
|     06 | 事業單位醫務室─廠護        |
|     07 | 社會福利機構               |
|     08 | 機關醫護室                 |
|     09 | 學校護理教育(實習指導老師) |
|     10 | 日間照護                   |
|     00 | 其他                       |


四、精神復健機構

| 權屬別 |                                  |
|--------+----------------------------------|
|     81 | 公立精神復健機構                 |
|     82 | 財團法人精神復健機構             |
|     83 | 其他法人附設精神復健機構         |
|     84 | 私立精神復健機構                 |
|     85 | 公立醫療機構附設精神復健機構     |
|     86 | 私立醫療機構附設精神復健機構     |
|     87 | 財團法人醫療機構附設精神復健機構 |
|     88 | 精神衛生團體附設精神復健機構     |


| 型態別 |              |
|--------+--------------|
|     08 | 社區復健中心 |
|     09 | 康復之家     |



五、其他醫事機構

| 權屬別 |                                  |
|--------+----------------------------------|
|     91 | 公立其他醫事機構                 |
|     92 | 財團法人其他醫事機構             |
|     93 | 其他法人附設其他醫事機構         |
|     94 | 私立其他醫事機構                 |
|     95 | 公立醫療機構附設其他醫事機構     |
|     96 | 私立醫療機構附設其他醫事機構     |
|     97 | 財團法人醫療機構附設其他醫事機構 |
|     98 | 其他                             |
|     xx | 不詳                             |



| 型態別 |                    |
|--------+--------------------|
|     01 | 醫事檢驗所         |
|     02 | 醫事放射所         |
|     03 | 物理治療所         |
|     04 | 職能治療所         |
|     05 | 鑲牙所             |
|     06 | 齒模製造技術員     |
|     07 | 國術損傷接骨技術員 |
|     00 | 其他               |
|     xx | 不詳               |


** man pdftotext

pdftotext [options] [PDF-file [text-file]]


Options

-f number
    Specifies the first page to convert.

-l number
    Specifies the last page to convert.

-layout
    Maintain (as best as possible) the original physical layout of the text. The default is to 'undo' physical layout (columns, hyphenation, etc.) and output the text in reading order.

-raw
    Keep the text in content stream order.  This is a hack which often "undoes" column formatting, etc.  Use of raw mode is no longer recommended.





 
