* pdftotext
  


** man pdftotext

pdftotext [options] [PDF-file [text-file]]


Options

-f number
    Specifies the first page to convert.

-l number
    Specifies the last page to convert.

-layout
    Maintain (as best as possible) the original physical layout of the text. The default is to 'undo' physical layout (columns, hyphenation, etc.) and output the text in reading order.

-raw
    Keep the text in content stream order.  This is a hack which often "undoes" column formatting, etc.  Use of raw mode is no longer recommended.


** source block 05, blank template, session, raw, sh

| step | goal                     | target           |
|------+--------------------------+------------------|

#+NAME:
#+HEADERS: :session
#+HEADERS: :results raw
#+BEGIN_SRC sh


#+END_SRC

#+RESULTS:




** source block 15, define pdf file name #+NAME: the_pdf_name_block

| step | goal                     | target           |
|------+--------------------------+------------------|
|      | define the pdf file name | the_pdf_filename |
|      |                          |                  |
|      | print the file name      |                  |

#+NAME: the_pdf_name_block
#+HEADERS: :session
#+HEADERS: :results raw
#+BEGIN_SRC sh


the_pdf_filename="en_codedescribe.pdf"


# echo "\$the_pdf_filename is:" $the_pdf_filename

# echo "the_dir_under_home is" $the_dir_under_home

# echo "the_file_name is" $the_file_name

# echo "the_pdf_path is"  $the_pdf_path

# printf "The current directory, by default, through the command pwd, is: " ; pwd

#+END_SRC






** source block 17, extract raw text between page f, l through pdftotext

#+NAME: raw_output
#+HEADERS: :noweb yes
#+HEADERS: :results raw
#+HEADERS: :session
#+BEGIN_SRC sh
<<the_pdf_name_block>>

pdftotext -f 1 -l 2 -raw $the_pdf_filename -
#+END_SRC



    

** source block 25, sed 

#+HEADERS: :noweb yes
#+HEADERS: :results raw
#+HEADERS: :session
#+BEGIN_SRC sh
<<the_pdf_name_block>>

raw_test=$(pdftotext -f 1 -l 2 -raw $the_pdf_filename -)

 echo $raw_test

 echo $raw_test | sed -r 's/[.]+/|/g' | sed -r 's/([0-9]+ )/\1\n/g'

# echo ${raw_test//\(\.+\)}     
# echo `expr "$stringZ" : '\(.......\)'`  
# echo `expr "$raw_test" : '\([\.]+\)'`  

# echo ${raw_test///.+B/,}
#+END_SRC

#+RESULTS:

B-I 目 錄 第二部份：代碼說明 評鑑等級...................................................................................................B-1 特約類別...................................................................................................B-3 權屬別及型態別其代號與名稱...............................................................B-4 特約狀況碼...............................................................................................B-9 醫事人員類別.........................................................................................B-10 病床類別.................................................................................................B-11 地區代碼、名稱、分局及郵遞區號.....................................................B-13 案件分類.................................................................................................B-26 健保卡就醫序號（預防保健服務時程代碼）.....................................B-35 部分負擔代號及相關規定.....................................................................B-40 就醫科別及細分科.................................................................................B-49 診療科別.................................................................................................B-51 專科醫師代號、科別.............................................................................B-53 特定治療項目代號.................................................................................B-55 給付類別.................................................................................................B-64 處方調劑方式.........................................................................................B-65 B-II 不適用 TW_DRGS 案件特殊註記.......................................................B-66 住院醫令類別.........................................................................................B-67 住院醫令代碼.........................................................................................B-68 診療部位申報方式.................................................................................B-72 單位屬性代號.........................................................................................B-74 加退保別說明.........................................................................................B-76 身份別說明.............................................................................................B-77 全民健康保險重大傷病範圍.................................................................B-78 串檔說明.................................................................................................B-79 ※本譯碼簿僅供參考，資料描述或代碼說明資訊如有異動，請逕自中 央健康保險署網站（http://www.nhi.gov.tw/）查閱。 
B-I 目 錄 第二部份：代碼說明 

| 評鑑等級                               | B-1  |
| 特約類別                               | B-3  |
| 權屬別及型態別其代號與名稱             | B-4  |
| 特約狀況碼                             | B-9  |
| 醫事人員類別                           | B-10 |
| 病床類別                               | B-11 |
| 地區代碼、名稱、分局及郵遞區號         | B-13 |
| 案件分類                               | B-26 |
| 健保卡就醫序號（預防保健服務時程代碼） | B-35 |
| 部分負擔代號及相關規定                 | B-40 |
| 就醫科別及細分科                       | B-49 |
| 診療科別                               | B-51 |
| 專科醫師代號、科別                     | B-53 |
| 特定治療項目代號                       | B-55 |
| 給付類別                               | B-64 |
| 處方調劑方式                           | B-65 |
| 不適用 TW_DRGS 案件特殊註記            | B-66 |
| 住院醫令類別                           | B-67 |
| 住院醫令代碼                           | B-68 |
| 診療部位申報方式                       | B-72 |
| 單位屬性代號                           | B-74 |
| 加退保別說明                           | B-76 |
| 身份別說明                             | B-77 |
| 全民健康保險重大傷病範圍               | B-78 |
| 串檔說明                               | B-79 |

※本譯碼簿僅供參考，資料描述或代碼說明資訊如有異動，請逕自中 央健康保險署網站（http://www|nhi|gov|tw/）查閱。 

B-I 目 錄 第二部份：代碼說明 評鑑等級...................................................................................................B-1 特約類別...................................................................................................B-3 權屬別及型態別其代號與名稱...............................................................B-4 特約狀況碼...............................................................................................B-9 醫事人員類別.........................................................................................B-10 病床類別.................................................................................................B-11 地區代碼、名稱、分局及郵遞區號.....................................................B-13 案件分類.................................................................................................B-26 健保卡就醫序號（預防保健服務時程代碼）.....................................B-35 部分負擔代號及相關規定.....................................................................B-40 就醫科別及細分科.................................................................................B-49 診療科別.................................................................................................B-51 專科醫師代號、科別.............................................................................B-53 特定治療項目代號.................................................................................B-55 給付類別.................................................................................................B-64 處方調劑方式.........................................................................................B-65 B-II 不適用 TW_DRGS 案件特殊註記.......................................................B-66 住院醫令類別.........................................................................................B-67 住院醫令代碼.........................................................................................B-68 診療部位申報方式.................................................................................B-72 單位屬性代號.........................................................................................B-74 加退保別說明.........................................................................................B-76 身份別說明.............................................................................................B-77 全民健康保險重大傷病範圍.................................................................B-78 串檔說明.................................................................................................B-79 ※本譯碼簿僅供參考，資料描述或代碼說明資訊如有異動，請逕自中 央健康保險署網站（http://www.nhi.gov.tw/）查閱。 
B-I 目 錄 第二部份：代碼說明 

| 評鑑等級                               |  1 |
| 特約類別                               |  3 |
| 權屬別及型態別其代號與名稱             |  4 |
| 特約狀況碼                             |  9 |
| 醫事人員類別                           | 10 |
| 病床類別                               | 11 |
| 地區代碼、名稱、分局及郵遞區號         | 13 |
| 案件分類                               | 26 |
| 健保卡就醫序號（預防保健服務時程代碼） | 35 |
| 部分負擔代號及相關規定                 | 40 |
| 就醫科別及細分科                       | 49 |
| 診療科別                               | 51 |
| 專科醫師代號、科別                     | 53 |
| 特定治療項目代號                       | 55 |
| 給付類別                               | 64 |
| 處方調劑方式                           | 65 |
| 不適用 TW_DRGS 案件特殊註記            | 66 |
| 住院醫令類別                           | 67 |
| 住院醫令代碼                           | 68 |
| 診療部位申報方式                       | 72 |
| 單位屬性代號                           | 74 |
| 加退保別說明                           | 76 |
| 身份別說明                             | 77 |
| 全民健康保險重大傷病範圍               | 78 |
| 串檔說明                               | 79 |

※本譯碼簿僅供參考，資料描述或代碼說明資訊如有異動，請逕自中央健康保險署網站（http://www.nhi.gov.tw/）查閱。

