* pdftotext
  


** man pdftotext

pdftotext [options] [PDF-file [text-file]]


Options

-f number
    Specifies the first page to convert.

-l number
    Specifies the last page to convert.

-layout
    Maintain (as best as possible) the original physical layout of the text. The default is to 'undo' physical layout (columns, hyphenation, etc.) and output the text in reading order.

-raw
    Keep the text in content stream order.  This is a hack which often "undoes" column formatting, etc.  Use of raw mode is no longer recommended.


** source block 05, blank template, session, raw, sh

| step | goal                     | target           |
|------+--------------------------+------------------|

#+NAME:
#+HEADERS: :session
#+HEADERS: :results raw
#+BEGIN_SRC sh


#+END_SRC

#+RESULTS:


** source block 07, long variable assignment

| step | goal                     | target           |
|------+--------------------------+------------------|

#+NAME:
#+HEADERS: :session
#+HEADERS: :results raw
#+BEGIN_SRC sh

test=$(printf 
'1'
2
3
)

# echo $test 

echo $test | sed -r 's/([0-9]) /\1 \n/g'

test1=$(echo $test | sed -r 's/([0-9]) /\1 \n/g')

echo 'test1 is' $test1

#+END_SRC

#+RESULTS:

test1 is
'1' 2 
3
test1 is '1' 2 3
1 
2 
3
test1 is 1 2 3
1 
2 
3
test1 is 1 2 3






** source block 15, define pdf file name #+NAME: the_pdf_name_block

| step | goal                     | target           |
|------+--------------------------+------------------|
|      | define the pdf file name | the_pdf_filename |
|      |                          |                  |
|      | print the file name      |                  |

#+NAME: the_pdf_name_block
#+HEADERS: :session
#+HEADERS: :results raw
#+BEGIN_SRC sh


the_pdf_filename="en_codedescribe.pdf"


# echo "\$the_pdf_filename is:" $the_pdf_filename

# echo "the_dir_under_home is" $the_dir_under_home

# echo "the_file_name is" $the_file_name

# echo "the_pdf_path is"  $the_pdf_path

# printf "The current directory, by default, through the command pwd, is: " ; pwd

#+END_SRC






** source block 17, extract raw text between page f, l through pdftotext

#+NAME: raw_output
#+HEADERS: :noweb yes
#+HEADERS: :results raw
#+HEADERS: :session
#+BEGIN_SRC sh
<<the_pdf_name_block>>

pdftotext -f 3 -l 4 -raw -nopgbrk $the_pdf_filename -
#+END_SRC


    

** source block 25, sed 

#+HEADERS: :noweb yes
#+HEADERS: :results raw
#+HEADERS: :session
#+BEGIN_SRC sh
 <<the_pdf_name_block>>

 raw_test=$(pdftotext -f 1 -l 2 -raw -nopgbrk $the_pdf_filename -)

 echo $raw_test

 echo $raw_test | sed -r 's/[.]{2,}/|/g' | sed -r 's/([0-9]+ )/\1\n/g'

#+END_SRC


** source block B, 代碼說明 B

#+HEADERS: :noweb yes
#+HEADERS: :results raw
#+HEADERS: :session
#+BEGIN_SRC sh
 <<the_pdf_name_block>>

 raw_test=$(pdftotext -f 1 -l 2 -raw -nopgbrk $the_pdf_filename -)

# echo $raw_test

 echo $raw_test | sed -r 's/[.]{2,}/|/g' | sed -r 's/([0-9]+ )/\1\n/g'

#+END_SRC


** source block B-1, 評鑑等級

#+HEADERS: :noweb yes
#+HEADERS: :results raw
#+HEADERS: :session
#+BEGIN_SRC sh
 <<the_pdf_name_block>>

 raw_test=$(pdftotext -f 3 -l 4 -nopgbrk -raw $the_pdf_filename -)

#  echo $raw_test | sed -r 's/([0-79][0-9]) /\n\1, /g'
#  echo $raw_test | sed -r 's/([0-79][0-9]) /\n\1, /g' | sed -r 's/( 8[89] )/,\1/g'
   echo $raw_test | sed -r 's/([0-79][0-9]) /\n\1, /g' | sed -r 's/( 8[89] )/,\1/g' | sed -r 's/( 評鑑制度 )/,\1/g' 


#+END_SRC







 

** source block B-3, 特約類別

#+HEADERS: :noweb yes
#+HEADERS: :results raw
#+HEADERS: :session
#+BEGIN_SRC sh
 <<the_pdf_name_block>>

            pdftotext -f 5 -l 5 -nopgbrk -raw $the_pdf_filename -

#+END_SRC

#+RESULTS:
B-3 特約類別 
|      |                  |                                                 |
| 代碼 | 名稱             | 備註                                            |
|------+------------------+-------------------------------------------------|
|    1 | 醫學中心         |                                                 |
|    2 | 區域醫院         |                                                 |
|    3 | 地區醫院         |                                                 |
|    4 | 基層院所         |                                                 |
|    5 | 特約藥局         |                                                 |
|    6 | 居家照護         |                                                 |
|    7 | 精神社區復健     |                                                 |
|    8 | 助產所           |                                                 |
|    9 | 特約醫事檢驗機構 | 92/3 由指定醫事檢驗機構改為特約醫事檢驗機構者。 |
|    A | 物理治療所       | 90/7/1 新增。                                   |
|    B | 放射治療機構     | 97/4 新增                                       |
|    C | 職能治療所       | 97/4 新增                                       |
| W、X | 不詳             |                                                 |







 
